<?php

namespace Models\Tables;

use Bitrix\Iblock\ElementTable;
use Bitrix\Iblock\PropertyEnumerationTable;
use Bitrix\Iblock\PropertyTable;
use Bitrix\Main\ArgumentException;
use Bitrix\Main\Data\Cache;
use Bitrix\Main\DB\SqlExpression;
use Bitrix\Main\Entity\ReferenceField;
use Bitrix\Main\NotImplementedException;
use Bitrix\Main\ObjectPropertyException;
use Bitrix\Main\ORM\Data\DataManager;
use Bitrix\Main\Entity\IntegerField;
use Bitrix\Main\Entity\StringField;
use Bitrix\Main\ORM\Data\DeleteResult;
use Bitrix\Main\ORM\Fields\DatetimeField;
use Bitrix\Main\ORM\Fields\ExpressionField;
use Bitrix\Main\ORM\Fields\Relations\Reference;
use Bitrix\Main\SystemException;
use CIBlockElement;
use \Models\AbstractIblockPropertyValuesTable;

class VisitTable extends AbstractIblockPropertyValuesTable
{
    const IBLOCK_ID = 21;

    public static function getMap(): array
    {
        $map = [
            'CLIENT' => new ReferenceField(
                'CLIENT',
                \Models\Tables\HospitalTable::class,
                ['=this.ID_KLIENTA' => 'ref.id']
            )
        ];
        return parent::getMap() + $map; // TODO: Change the autogenerated stub
    }

}